import type { EraProfile, EraType } from "./types";

export const ERA_LIBRARY: Record<EraType, EraProfile> = {
  golden: {
    id: "golden",
    name: "黄金时代",
    description: "资源丰沛，秩序稳定，叙述却可能过于乐观。",
    baseHabitability: 82,
    baseAcceptance: 78,
    baseTech: 70,
    baseCapacity: 120000,
    baseTrust: 72,
    tone: "optimistic",
  },
  war: {
    id: "war",
    name: "战乱年代",
    description: "冲突四起，城邦易碎，任何人口流动都伴随代价。",
    baseHabitability: 45,
    baseAcceptance: 32,
    baseTech: 38,
    baseCapacity: 50000,
    baseTrust: 28,
    tone: "pessimistic",
  },
  ecological_collapse: {
    id: "ecological_collapse",
    name: "生态崩溃",
    description: "气候失衡，土地贫瘠，生存本身就是赌博。",
    baseHabitability: 18,
    baseAcceptance: 40,
    baseTech: 22,
    baseCapacity: 18000,
    baseTrust: 36,
    tone: "liar",
  },
  tech_singularity: {
    id: "tech_singularity",
    name: "科技奇点",
    description: "技术飞跃，规则改写，但人群未必因此安全。",
    baseHabitability: 74,
    baseAcceptance: 55,
    baseTech: 95,
    baseCapacity: 160000,
    baseTrust: 60,
    tone: "reliable",
  },
  pseudo_prosperity: {
    id: "pseudo_prosperity",
    name: "伪繁荣",
    description: "表面繁华，内部空洞，叙述常常比现实更亮。",
    baseHabitability: 58,
    baseAcceptance: 50,
    baseTech: 42,
    baseCapacity: 90000,
    baseTrust: 42,
    tone: "optimistic",
  },
  winter: {
    id: "winter",
    name: "寒冬时代",
    description: "漫长的寒潮吞没道路，资源与耐心都在消耗。",
    baseHabitability: 24,
    baseAcceptance: 28,
    baseTech: 30,
    baseCapacity: 22000,
    baseTrust: 33,
    tone: "pessimistic",
  },
  plague: {
    id: "plague",
    name: "瘟疫蔓延",
    description: "疾病、隔离与恐惧共同统治年代。",
    baseHabitability: 30,
    baseAcceptance: 24,
    baseTech: 34,
    baseCapacity: 26000,
    baseTrust: 26,
    tone: "liar",
  },
  revival: {
    id: "revival",
    name: "复兴纪元",
    description: "废墟中重新长出秩序，世界缓慢恢复呼吸。",
    baseHabitability: 66,
    baseAcceptance: 68,
    baseTech: 54,
    baseCapacity: 76000,
    baseTrust: 66,
    tone: "reliable",
  },
  totalitarian: {
    id: "totalitarian",
    name: "极权时代",
    description: "秩序高压而稳定，接纳度常被压到最低。",
    baseHabitability: 54,
    baseAcceptance: 18,
    baseTech: 64,
    baseCapacity: 68000,
    baseTrust: 22,
    tone: "liar",
  },
  void: {
    id: "void",
    name: "真空荒芜",
    description: "寂静、空旷、几乎没有文明可言。",
    baseHabitability: 8,
    baseAcceptance: 10,
    baseTech: 6,
    baseCapacity: 8000,
    baseTrust: 14,
    tone: "pessimistic",
  },
};

export const ERA_ORDER: EraType[] = [
  "golden",
  "war",
  "ecological_collapse",
  "tech_singularity",
  "pseudo_prosperity",
  "winter",
  "plague",
  "revival",
  "totalitarian",
  "void",
];

/** 根据整局演化索引生成时代（循环） */
export function createEra(index: number): EraProfile {
  const eraType = ERA_ORDER[index % ERA_ORDER.length];
  return ERA_LIBRARY[eraType];
}
